// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Js0rWjUuh9MLN2vtNVLhSJ9Czc2_byw',
    appId: '1:790206159667:web:5a53445ef077371c0f7c46',
    messagingSenderId: '790206159667',
    projectId: 'authproject-d94c4',
    authDomain: 'authproject-d94c4.firebaseapp.com',
    storageBucket: 'authproject-d94c4.appspot.com',
    measurementId: 'G-S0J7QC0DWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGDG3R-vS-c96oiUPTAkpZCWDlDPnqsw',
    appId: '1:790206159667:android:7b7b2c245bbd8ad10f7c46',
    messagingSenderId: '790206159667',
    projectId: 'authproject-d94c4',
    storageBucket: 'authproject-d94c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--_NY1bARG4LW0bOUIrLSyHMEcsOpr18',
    appId: '1:790206159667:ios:cbaccfa5ab6f750c0f7c46',
    messagingSenderId: '790206159667',
    projectId: 'authproject-d94c4',
    storageBucket: 'authproject-d94c4.appspot.com',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--_NY1bARG4LW0bOUIrLSyHMEcsOpr18',
    appId: '1:790206159667:ios:cbaccfa5ab6f750c0f7c46',
    messagingSenderId: '790206159667',
    projectId: 'authproject-d94c4',
    storageBucket: 'authproject-d94c4.appspot.com',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Js0rWjUuh9MLN2vtNVLhSJ9Czc2_byw',
    appId: '1:790206159667:web:0ec88fcfb1229ad70f7c46',
    messagingSenderId: '790206159667',
    projectId: 'authproject-d94c4',
    authDomain: 'authproject-d94c4.firebaseapp.com',
    storageBucket: 'authproject-d94c4.appspot.com',
    measurementId: 'G-GHM3G6WXFC',
  );
}
